version: "3"

services:

  postgres:
    image: postgres:15
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres"]

  app:
    build: .
    restart: always
    ports:
      - ${APP_PORT}:5000
    env_file:       
      - .env
    depends_on:
      - postgres
    volumes:
      - ./app/:/app/
    command: ["flask", "run", "--host", "0.0.0.0", "--port", "5000"]
volumes:
  postgres_data:
